apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
        app: geolocation
    spec:
      containers:
        - name: geolocation
          image: 207650910957.dkr.ecr.us-east-1.amazonaws.com/geolo:2.0
          ports:
            - containerPort: 8082