apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: ui-container
        image: edennolan2021/ui:1.0
        env:
          - name: AUTH_HOST
            value: auth
          - name: AUTH_PORT
            value: "8080"
          - name: WEATHER_HOST
            value: weather-service
          - name: WEATHER_PORT
            value: "5000"
          - name: REDIS_USER
            value: redis
          - name: REDIS_PASSWORD
            value: redis
      restartPolicy: Always