apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  ports:                           
    - protocol: TCP
      port: 80
      targetPort: 80