apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
spec:
  selector:
    app: wordpress
    tier: mysql
  type: ClusterIP
  ports:                           
    - protocol: TCP
      port: 3306
      targetPort: 3306